version: '3'

services:
  user_service:
    build: ./user_service
    ports:
      - "5001:5000"
    volumes:
      - ./user_service:/code/user_service:ro
    command: python /code/user_service/app.py

  message_service:
    build: ./message_service
    ports:
      - "5002:5000"
    volumes:
      - ./message_service:/code/message_service:ro
    command: python /code/message_service/app.py

  auth_service:
    build: ./auth_service
    ports:
      - "5003:5000"
    volumes:
      - ./auth_service:/code/auth_service:ro
    command: python /code/auth_service/app.py
